name: Build and Release Go Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Go Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1" # Adjust the version as per your needs

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Compile binary
        run: |
          go mod download
          go get -u github.com/go-ping/ping
          go get -u golang.org/x/net
          go mod download
          go build -o ping_server_checker ./main.go

      - name: Archive binary
        run: zip -r ping_server_checker.zip ping_server_checker

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ping_server_checker
          path: ping_server_checker.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ping_server_checker

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ping_server_checker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
